(setq perldoc-obarray (make-vector 1519 nil))
;; Functions
(mapc (lambda (func)
         (set (intern func perldoc-obarray) t))
'(
"-A" "-B" "-C" "-M" "-O" "-R" "-S" "-T" "-W" "-X" "-b" "-c" "-d" "-e" "-f"
"-g" "-k" "-l" "-o" "-p" "-r" "-s" "-t" "-u" "-w" "-x" "-z" "abs" "accept"
"alarm" "atan2" "bind" "binmode" "bless" "caller" "chdir" "chmod" "chomp"
"chop" "chown" "chr" "chroot" "close" "closedir" "connect" "continue" "cos"
"crypt" "dbmclose" "dbmopen" "defined" "delete" "die" "do" "dump" "each"
"endgrent" "endhostent" "endnetent" "endprotoent" "endpwent" "endservent"
"eof" "eval" "exec" "exists" "exit" "exp" "fcntl" "fileno" "flock" "fork"
"format" "formline" "getc" "getgrent" "getgrgid" "getgrnam" "gethostbyaddr"
"gethostbyname" "gethostent" "getlogin" "getnetbyaddr" "getnetbyname"
"getnetent" "getpeername" "getpgrp" "getppid" "getpriority"
"getprotobyname" "getprotobynumber" "getprotoent" "getpwent" "getpwnam"
"getpwuid" "getservbyname" "getservbyport" "getservent" "getsockname"
"getsockopt" "glob" "gmtime" "goto" "grep" "hex" "import" "index" "int"
"ioctl" "join" "keys" "kill" "last" "lc" "lcfirst" "length" "link" "listen"
"local" "localtime" "lock" "log" "lstat" "m" "map" "mkdir" "msgctl"
"msgget" "msgrcv" "msgsnd" "my" "next" "no" "oct" "open" "opendir" "ord"
"our" "pack" "package" "pipe" "pop" "pos" "print" "printf" "prototype"
"push" "q" "qq" "qr" "quotemeta" "qw" "qx" "rand" "read" "readdir"
"readline" "readlink" "readpipe" "recv" "redo" "ref" "rename" "require"
"reset" "return" "reverse" "rewinddir" "rindex" "rmdir" "s" "scalar" "seek"
"seekdir" "select" "semctl" "semget" "semop" "send" "setgrent" "sethostent"
"setnetent" "setpgrp" "setpriority" "setprotoent" "setpwent" "setservent"
"setsockopt" "shift" "shmctl" "shmget" "shmread" "shmwrite" "shutdown"
"sin" "sleep" "socket" "socketpair" "sort" "splice" "split" "sprintf"
"sqrt" "srand" "stat" "study" "sub" "substr" "symlink" "syscall" "sysopen"
"sysread" "sysseek" "system" "syswrite" "tell" "telldir" "tie" "tied"
"time" "times" "tr" "truncate" "uc" "ucfirst" "umask" "undef" "unlink"
"unpack" "unshift" "untie" "use" "utime" "values" "vec" "wait" "waitpid"
"wantarray" "warn" "write" "y"))

;; Modules
(mapc (lambda (mod)
         (intern mod perldoc-obarray))
'(
"5.8.8::AppConfig" "5.8.8::AppConfig::Args" "5.8.8::AppConfig::CGI"
"5.8.8::AppConfig::File" "5.8.8::AppConfig::Getopt"
"5.8.8::AppConfig::State" "5.8.8::AppConfig::Sys" "5.8.8::Bundle::LWP"
"5.8.8::Compress::Zlib" "5.8.8::File::GlobMapper" "5.8.8::File::Listing"
"5.8.8::HTML::Form" "5.8.8::HTML::Tagset" "5.8.8::HTTP::Cookies"
"5.8.8::HTTP::Cookies::Microsoft" "5.8.8::HTTP::Cookies::Netscape"
"5.8.8::HTTP::Daemon" "5.8.8::HTTP::Date" "5.8.8::HTTP::Headers"
"5.8.8::HTTP::Headers::Auth" "5.8.8::HTTP::Headers::ETag"
"5.8.8::HTTP::Headers::Util" "5.8.8::HTTP::Message"
"5.8.8::HTTP::Negotiate" "5.8.8::HTTP::Request"
"5.8.8::HTTP::Request::Common" "5.8.8::HTTP::Response"
"5.8.8::HTTP::Status" "5.8.8::IO::Compress::Adapter::Deflate"
"5.8.8::IO::Compress::Adapter::Identity" "5.8.8::IO::Compress::Base"
"5.8.8::IO::Compress::Base::Common" "5.8.8::IO::Compress::Deflate"
"5.8.8::IO::Compress::Gzip" "5.8.8::IO::Compress::Gzip::Constants"
"5.8.8::IO::Compress::RawDeflate" "5.8.8::IO::Compress::Zip"
"5.8.8::IO::Compress::Zip::Constants"
"5.8.8::IO::Compress::Zlib::Constants" "5.8.8::IO::Compress::Zlib::Extra"
"5.8.8::IO::Uncompress::Adapter::Identity"
"5.8.8::IO::Uncompress::Adapter::Inflate"
"5.8.8::IO::Uncompress::AnyInflate" "5.8.8::IO::Uncompress::AnyUncompress"
"5.8.8::IO::Uncompress::Base" "5.8.8::IO::Uncompress::Gunzip"
"5.8.8::IO::Uncompress::Inflate" "5.8.8::IO::Uncompress::RawInflate"
"5.8.8::IO::Uncompress::Unzip" "5.8.8::LWP" "5.8.8::LWP::Authen::Basic"
"5.8.8::LWP::Authen::Digest" "5.8.8::LWP::Authen::Ntlm"
"5.8.8::LWP::ConnCache" "5.8.8::LWP::Debug" "5.8.8::LWP::DebugFile"
"5.8.8::LWP::MediaTypes" "5.8.8::LWP::MemberMixin" "5.8.8::LWP::Protocol"
"5.8.8::LWP::Protocol::GHTTP" "5.8.8::LWP::Protocol::cpan"
"5.8.8::LWP::Protocol::data" "5.8.8::LWP::Protocol::file"
"5.8.8::LWP::Protocol::ftp" "5.8.8::LWP::Protocol::gopher"
"5.8.8::LWP::Protocol::http" "5.8.8::LWP::Protocol::http10"
"5.8.8::LWP::Protocol::https" "5.8.8::LWP::Protocol::https10"
"5.8.8::LWP::Protocol::loopback" "5.8.8::LWP::Protocol::mailto"
"5.8.8::LWP::Protocol::nntp" "5.8.8::LWP::Protocol::nogo"
"5.8.8::LWP::RobotUA" "5.8.8::LWP::Simple" "5.8.8::LWP::UserAgent"
"5.8.8::Net::HTTP" "5.8.8::Net::HTTP::Methods" "5.8.8::Net::HTTP::NB"
"5.8.8::Net::HTTPS" "5.8.8::Parse::ALex" "5.8.8::Parse::CLex"
"5.8.8::Parse::Lex" "5.8.8::Parse::LexEvent" "5.8.8::Parse::Template"
"5.8.8::Parse::Token" "5.8.8::Parse::Token-t" "5.8.8::Parse::Trace"
"5.8.8::Parse::YYLex" "5.8.8::Parse::Yapp" "5.8.8::Parse::Yapp::Driver"
"5.8.8::Parse::Yapp::Grammar" "5.8.8::Parse::Yapp::Lalr"
"5.8.8::Parse::Yapp::Options" "5.8.8::Parse::Yapp::Output"
"5.8.8::Parse::Yapp::Parse" "5.8.8::URI" "5.8.8::URI::Escape"
"5.8.8::URI::Heuristic" "5.8.8::URI::QueryParam" "5.8.8::URI::Split"
"5.8.8::URI::URL" "5.8.8::URI::WithBase" "5.8.8::URI::_foreign"
"5.8.8::URI::_generic" "5.8.8::URI::_ldap" "5.8.8::URI::_login"
"5.8.8::URI::_query" "5.8.8::URI::_segment" "5.8.8::URI::_server"
"5.8.8::URI::_userpass" "5.8.8::URI::data" "5.8.8::URI::file"
"5.8.8::URI::file::Base" "5.8.8::URI::file::FAT" "5.8.8::URI::file::Mac"
"5.8.8::URI::file::OS2" "5.8.8::URI::file::QNX" "5.8.8::URI::file::Unix"
"5.8.8::URI::file::Win32" "5.8.8::URI::ftp" "5.8.8::URI::gopher"
"5.8.8::URI::http" "5.8.8::URI::https" "5.8.8::URI::ldap"
"5.8.8::URI::ldapi" "5.8.8::URI::ldaps" "5.8.8::URI::mailto"
"5.8.8::URI::mms" "5.8.8::URI::news" "5.8.8::URI::nntp" "5.8.8::URI::pop"
"5.8.8::URI::rlogin" "5.8.8::URI::rsync" "5.8.8::URI::rtsp"
"5.8.8::URI::rtspu" "5.8.8::URI::sip" "5.8.8::URI::sips"
"5.8.8::URI::snews" "5.8.8::URI::ssh" "5.8.8::URI::telnet"
"5.8.8::URI::tn3270" "5.8.8::URI::urn" "5.8.8::URI::urn::isbn"
"5.8.8::URI::urn::oid" "5.8.8::WWW::RobotRules"
"5.8.8::WWW::RobotRules::AnyDBM_File"
"5.8.8::i686-linux::Compress::Raw::Zlib"
"5.8.8::i686-linux::HTML::Entities" "5.8.8::i686-linux::HTML::Filter"
"5.8.8::i686-linux::HTML::HeadParser" "5.8.8::i686-linux::HTML::LinkExtor"
"5.8.8::i686-linux::HTML::Parser" "5.8.8::i686-linux::HTML::PullParser"
"5.8.8::i686-linux::HTML::TokeParser" "5.8.8::i686-linux::Image::Magick"
"5.8.8::i686-linux::Template" "5.8.8::i686-linux::Template::Base"
"5.8.8::i686-linux::Template::Config"
"5.8.8::i686-linux::Template::Constants"
"5.8.8::i686-linux::Template::Context"
"5.8.8::i686-linux::Template::Directive"
"5.8.8::i686-linux::Template::Document"
"5.8.8::i686-linux::Template::Exception" "5.8.8::i686-linux::Template::FAQ"
"5.8.8::i686-linux::Template::Filters"
"5.8.8::i686-linux::Template::Grammar"
"5.8.8::i686-linux::Template::Iterator"
"5.8.8::i686-linux::Template::Library::HTML"
"5.8.8::i686-linux::Template::Library::PostScript"
"5.8.8::i686-linux::Template::Library::Splash"
"5.8.8::i686-linux::Template::Manual"
"5.8.8::i686-linux::Template::Manual::Config"
"5.8.8::i686-linux::Template::Manual::Credits"
"5.8.8::i686-linux::Template::Manual::Directives"
"5.8.8::i686-linux::Template::Manual::Filters"
"5.8.8::i686-linux::Template::Manual::Internals"
"5.8.8::i686-linux::Template::Manual::Intro"
"5.8.8::i686-linux::Template::Manual::Plugins"
"5.8.8::i686-linux::Template::Manual::Refs"
"5.8.8::i686-linux::Template::Manual::Syntax"
"5.8.8::i686-linux::Template::Manual::VMethods"
"5.8.8::i686-linux::Template::Manual::Variables"
"5.8.8::i686-linux::Template::Manual::Views"
"5.8.8::i686-linux::Template::Modules"
"5.8.8::i686-linux::Template::Namespace::Constants"
"5.8.8::i686-linux::Template::Parser" "5.8.8::i686-linux::Template::Plugin"
"5.8.8::i686-linux::Template::Plugin::Autoformat"
"5.8.8::i686-linux::Template::Plugin::CGI"
"5.8.8::i686-linux::Template::Plugin::Datafile"
"5.8.8::i686-linux::Template::Plugin::Date"
"5.8.8::i686-linux::Template::Plugin::Directory"
"5.8.8::i686-linux::Template::Plugin::Dumper"
"5.8.8::i686-linux::Template::Plugin::File"
"5.8.8::i686-linux::Template::Plugin::Filter"
"5.8.8::i686-linux::Template::Plugin::Format"
"5.8.8::i686-linux::Template::Plugin::HTML"
"5.8.8::i686-linux::Template::Plugin::Image"
"5.8.8::i686-linux::Template::Plugin::Iterator"
"5.8.8::i686-linux::Template::Plugin::Pod"
"5.8.8::i686-linux::Template::Plugin::Procedural"
"5.8.8::i686-linux::Template::Plugin::String"
"5.8.8::i686-linux::Template::Plugin::Table"
"5.8.8::i686-linux::Template::Plugin::URL"
"5.8.8::i686-linux::Template::Plugin::View"
"5.8.8::i686-linux::Template::Plugin::Wrap"
"5.8.8::i686-linux::Template::Plugins"
"5.8.8::i686-linux::Template::Provider"
"5.8.8::i686-linux::Template::Service" "5.8.8::i686-linux::Template::Stash"
"5.8.8::i686-linux::Template::Stash::Context"
"5.8.8::i686-linux::Template::Stash::XS"
"5.8.8::i686-linux::Template::Test" "5.8.8::i686-linux::Template::Toolkit"
"5.8.8::i686-linux::Template::Tools::tpage"
"5.8.8::i686-linux::Template::Tools::ttree"
"5.8.8::i686-linux::Template::Tutorial"
"5.8.8::i686-linux::Template::Tutorial::Datafile"
"5.8.8::i686-linux::Template::Tutorial::Web"
"5.8.8::i686-linux::Template::VMethods" "5.8.8::i686-linux::Template::View"
"5.8.8::i686-linux::XML::Parser" "5.8.8::i686-linux::XML::Parser::Expat"
"5.8.8::i686-linux::XML::Parser::Style::Debug"
"5.8.8::i686-linux::XML::Parser::Style::Objects"
"5.8.8::i686-linux::XML::Parser::Style::Stream"
"5.8.8::i686-linux::XML::Parser::Style::Subs"
"5.8.8::i686-linux::XML::Parser::Style::Tree" "5.8.8::lwpcook"
"5.8.8::lwptut" "AnyDBM_File" "AppConfig" "AppConfig::Args"
"AppConfig::CGI" "AppConfig::File" "AppConfig::Getopt" "AppConfig::State"
"AppConfig::Sys" "Attribute::Handlers" "AutoLoader" "AutoSplit" "B"
"B::Asmdata" "B::Assembler" "B::Bblock" "B::Bytecode" "B::C" "B::CC"
"B::Concise" "B::Debug" "B::Deparse" "B::Disassembler" "B::Lint"
"B::Showlex" "B::Stackobj" "B::Stash" "B::Terse" "B::Xref" "Benchmark"
"Bundle::LWP" "ByteLoader" "CGI" "CGI::Apache" "CGI::Carp" "CGI::Cookie"
"CGI::Fast" "CGI::Pretty" "CGI::Push" "CGI::Switch" "CGI::Util" "CPAN"
"CPAN::Config" "CPAN::FirstTime" "CPAN::Nox" "Carp" "Carp::Heavy"
"Class::ISA" "Class::Struct" "Compress::Raw::Zlib" "Compress::Zlib"
"Config" "Cwd" "DB" "DBM_Filter" "DBM_Filter::compress"
"DBM_Filter::encode" "DBM_Filter::int32" "DBM_Filter::null"
"DBM_Filter::utf8" "DB_File" "Data::Dumper" "Devel::DProf" "Devel::PPPort"
"Devel::Peek" "Devel::SelfStubber" "Digest" "Digest::MD5" "Digest::base"
"Digest::file" "DirHandle" "Dumpvalue" "DynaLoader" "Encode"
"Encode::Alias" "Encode::Byte" "Encode::CJKConstants" "Encode::CN"
"Encode::CN::HZ" "Encode::Config" "Encode::EBCDIC" "Encode::Encoder"
"Encode::Encoding" "Encode::Guess" "Encode::JP" "Encode::JP::H2Z"
"Encode::JP::JIS7" "Encode::KR" "Encode::KR::2022_KR"
"Encode::MIME::Header" "Encode::MIME::Header::ISO_2022_JP" "Encode::PerlIO"
"Encode::Supported" "Encode::Symbol" "Encode::TW" "Encode::Unicode"
"Encode::Unicode::UTF7" "English" "Env" "Errno" "Exporter"
"Exporter::Heavy" "ExtUtils::Command" "ExtUtils::Command::MM"
"ExtUtils::Constant" "ExtUtils::Constant::Base" "ExtUtils::Constant::Utils"
"ExtUtils::Constant::XS" "ExtUtils::Embed" "ExtUtils::Install"
"ExtUtils::Installed" "ExtUtils::Liblist" "ExtUtils::Liblist::Kid"
"ExtUtils::MM" "ExtUtils::MM_AIX" "ExtUtils::MM_Any" "ExtUtils::MM_BeOS"
"ExtUtils::MM_Cygwin" "ExtUtils::MM_DOS" "ExtUtils::MM_Darwin"
"ExtUtils::MM_MacOS" "ExtUtils::MM_NW5" "ExtUtils::MM_OS2"
"ExtUtils::MM_QNX" "ExtUtils::MM_UWIN" "ExtUtils::MM_Unix"
"ExtUtils::MM_VMS" "ExtUtils::MM_VOS" "ExtUtils::MM_Win32"
"ExtUtils::MM_Win95" "ExtUtils::MY" "ExtUtils::MakeMaker"
"ExtUtils::MakeMaker::Config" "ExtUtils::MakeMaker::FAQ"
"ExtUtils::MakeMaker::Tutorial" "ExtUtils::MakeMaker::bytes"
"ExtUtils::MakeMaker::vmsish" "ExtUtils::Manifest" "ExtUtils::Miniperl"
"ExtUtils::Mkbootstrap" "ExtUtils::Mksymlists" "ExtUtils::Packlist"
"ExtUtils::testlib" "Fatal" "Fcntl" "File::Basename" "File::CheckTree"
"File::Compare" "File::Copy" "File::DosGlob" "File::Find" "File::Glob"
"File::GlobMapper" "File::Listing" "File::Path" "File::Spec"
"File::Spec::Cygwin" "File::Spec::Epoc" "File::Spec::Functions"
"File::Spec::Mac" "File::Spec::OS2" "File::Spec::Unix" "File::Spec::VMS"
"File::Spec::Win32" "File::Temp" "File::stat" "FileCache" "FileHandle"
"Filter::Simple" "Filter::Util::Call" "FindBin" "Getopt::Long"
"Getopt::Std" "HTML::Entities" "HTML::Filter" "HTML::Form"
"HTML::HeadParser" "HTML::LinkExtor" "HTML::Parser" "HTML::PullParser"
"HTML::Tagset" "HTML::TokeParser" "HTTP::Cookies"
"HTTP::Cookies::Microsoft" "HTTP::Cookies::Netscape" "HTTP::Daemon"
"HTTP::Date" "HTTP::Headers" "HTTP::Headers::Auth" "HTTP::Headers::ETag"
"HTTP::Headers::Util" "HTTP::Message" "HTTP::Negotiate" "HTTP::Request"
"HTTP::Request::Common" "HTTP::Response" "HTTP::Status" "Hash::Util"
"I18N::Collate" "I18N::LangTags" "I18N::LangTags::Detect"
"I18N::LangTags::List" "I18N::Langinfo" "IO"
"IO::Compress::Adapter::Deflate" "IO::Compress::Adapter::Identity"
"IO::Compress::Base" "IO::Compress::Base::Common" "IO::Compress::Deflate"
"IO::Compress::Gzip" "IO::Compress::Gzip::Constants"
"IO::Compress::RawDeflate" "IO::Compress::Zip"
"IO::Compress::Zip::Constants" "IO::Compress::Zlib::Constants"
"IO::Compress::Zlib::Extra" "IO::Dir" "IO::File" "IO::Handle" "IO::Pipe"
"IO::Poll" "IO::Seekable" "IO::Select" "IO::Socket" "IO::Socket::INET"
"IO::Socket::UNIX" "IO::Uncompress::Adapter::Identity"
"IO::Uncompress::Adapter::Inflate" "IO::Uncompress::AnyInflate"
"IO::Uncompress::AnyUncompress" "IO::Uncompress::Base"
"IO::Uncompress::Gunzip" "IO::Uncompress::Inflate"
"IO::Uncompress::RawInflate" "IO::Uncompress::Unzip" "IPC::Msg"
"IPC::Open2" "IPC::Open3" "IPC::Semaphore" "IPC::SysV" "Image::Magick"
"LWP" "LWP::Authen::Basic" "LWP::Authen::Digest" "LWP::Authen::Ntlm"
"LWP::ConnCache" "LWP::Debug" "LWP::DebugFile" "LWP::MediaTypes"
"LWP::MemberMixin" "LWP::Protocol" "LWP::Protocol::GHTTP"
"LWP::Protocol::cpan" "LWP::Protocol::data" "LWP::Protocol::file"
"LWP::Protocol::ftp" "LWP::Protocol::gopher" "LWP::Protocol::http"
"LWP::Protocol::http10" "LWP::Protocol::https" "LWP::Protocol::https10"
"LWP::Protocol::loopback" "LWP::Protocol::mailto" "LWP::Protocol::nntp"
"LWP::Protocol::nogo" "LWP::RobotUA" "LWP::Simple" "LWP::UserAgent"
"List::Util" "Locale::Constants" "Locale::Country" "Locale::Currency"
"Locale::Language" "Locale::Maketext" "Locale::Maketext::Guts"
"Locale::Maketext::GutsLoader" "Locale::Maketext::TPJ13" "Locale::Script"
"MIME::Base64" "MIME::QuotedPrint" "Math::BigFloat" "Math::BigFloat::Trace"
"Math::BigInt" "Math::BigInt::Calc" "Math::BigInt::CalcEmu"
"Math::BigInt::Trace" "Math::BigRat" "Math::Complex" "Math::Trig" "Memoize"
"Memoize::AnyDBM_File" "Memoize::Expire" "Memoize::ExpireFile"
"Memoize::ExpireTest" "Memoize::NDBM_File" "Memoize::SDBM_File"
"Memoize::Storable" "NEXT" "Net::Cmd" "Net::Config" "Net::Domain"
"Net::FTP" "Net::FTP::A" "Net::FTP::E" "Net::FTP::I" "Net::FTP::L"
"Net::FTP::dataconn" "Net::HTTP" "Net::HTTP::Methods" "Net::HTTP::NB"
"Net::HTTPS" "Net::NNTP" "Net::Netrc" "Net::POP3" "Net::Ping" "Net::SMTP"
"Net::Time" "Net::hostent" "Net::libnetFAQ" "Net::netent" "Net::protoent"
"Net::servent" "O" "Opcode" "POSIX" "Parse::ALex" "Parse::CLex"
"Parse::Lex" "Parse::LexEvent" "Parse::Template" "Parse::Token"
"Parse::Token-t" "Parse::Trace" "Parse::YYLex" "Parse::Yapp"
"Parse::Yapp::Driver" "Parse::Yapp::Grammar" "Parse::Yapp::Lalr"
"Parse::Yapp::Options" "Parse::Yapp::Output" "Parse::Yapp::Parse" "PerlIO"
"PerlIO::encoding" "PerlIO::scalar" "PerlIO::via"
"PerlIO::via::QuotedPrint" "Pod::Checker" "Pod::Find" "Pod::Functions"
"Pod::Html" "Pod::InputObjects" "Pod::LaTeX" "Pod::Man" "Pod::ParseLink"
"Pod::ParseUtils" "Pod::Parser" "Pod::Perldoc" "Pod::Perldoc::BaseTo"
"Pod::Perldoc::GetOptsOO" "Pod::Perldoc::ToChecker" "Pod::Perldoc::ToMan"
"Pod::Perldoc::ToNroff" "Pod::Perldoc::ToPod" "Pod::Perldoc::ToRtf"
"Pod::Perldoc::ToText" "Pod::Perldoc::ToTk" "Pod::Perldoc::ToXml"
"Pod::PlainText" "Pod::Plainer" "Pod::Select" "Pod::Text"
"Pod::Text::Color" "Pod::Text::Overstrike" "Pod::Text::Termcap"
"Pod::Usage" "SDBM_File" "Safe" "Scalar::Util" "Search::Dict" "SelectSaver"
"SelfLoader" "Shell" "Socket" "Storable" "Switch" "Symbol" "Sys::Hostname"
"Sys::Syslog" "Template" "Template::Base" "Template::Config"
"Template::Constants" "Template::Context" "Template::Directive"
"Template::Document" "Template::Exception" "Template::FAQ"
"Template::Filters" "Template::Grammar" "Template::Iterator"
"Template::Library::HTML" "Template::Library::PostScript"
"Template::Library::Splash" "Template::Manual" "Template::Manual::Config"
"Template::Manual::Credits" "Template::Manual::Directives"
"Template::Manual::Filters" "Template::Manual::Internals"
"Template::Manual::Intro" "Template::Manual::Plugins"
"Template::Manual::Refs" "Template::Manual::Syntax"
"Template::Manual::VMethods" "Template::Manual::Variables"
"Template::Manual::Views" "Template::Modules"
"Template::Namespace::Constants" "Template::Parser" "Template::Plugin"
"Template::Plugin::Autoformat" "Template::Plugin::CGI"
"Template::Plugin::Datafile" "Template::Plugin::Date"
"Template::Plugin::Directory" "Template::Plugin::Dumper"
"Template::Plugin::File" "Template::Plugin::Filter"
"Template::Plugin::Format" "Template::Plugin::HTML"
"Template::Plugin::Image" "Template::Plugin::Iterator"
"Template::Plugin::Pod" "Template::Plugin::Procedural"
"Template::Plugin::String" "Template::Plugin::Table"
"Template::Plugin::URL" "Template::Plugin::View" "Template::Plugin::Wrap"
"Template::Plugins" "Template::Provider" "Template::Service"
"Template::Stash" "Template::Stash::Context" "Template::Stash::XS"
"Template::Test" "Template::Toolkit" "Template::Tools::tpage"
"Template::Tools::ttree" "Template::Tutorial"
"Template::Tutorial::Datafile" "Template::Tutorial::Web"
"Template::VMethods" "Template::View" "Term::ANSIColor" "Term::Cap"
"Term::Complete" "Term::ReadLine" "Test" "Test::Builder"
"Test::Builder::Module" "Test::Builder::Tester"
"Test::Builder::Tester::Color" "Test::Harness" "Test::Harness::Assert"
"Test::Harness::Iterator" "Test::Harness::Point" "Test::Harness::Straps"
"Test::Harness::TAP" "Test::More" "Test::Simple" "Test::Tutorial"
"Text::Abbrev" "Text::Balanced" "Text::ParseWords" "Text::Soundex"
"Text::Tabs" "Text::Wrap" "Thread" "Thread::Queue" "Thread::Semaphore"
"Tie::Array" "Tie::File" "Tie::Handle" "Tie::Hash" "Tie::Memoize"
"Tie::RefHash" "Tie::Scalar" "Tie::SubstrHash" "Time::HiRes" "Time::Local"
"Time::gmtime" "Time::localtime" "Time::tm" "UNIVERSAL" "URI" "URI::Escape"
"URI::Heuristic" "URI::QueryParam" "URI::Split" "URI::URL" "URI::WithBase"
"URI::_foreign" "URI::_generic" "URI::_ldap" "URI::_login" "URI::_query"
"URI::_segment" "URI::_server" "URI::_userpass" "URI::data" "URI::file"
"URI::file::Base" "URI::file::FAT" "URI::file::Mac" "URI::file::OS2"
"URI::file::QNX" "URI::file::Unix" "URI::file::Win32" "URI::ftp"
"URI::gopher" "URI::http" "URI::https" "URI::ldap" "URI::ldapi"
"URI::ldaps" "URI::mailto" "URI::mms" "URI::news" "URI::nntp" "URI::pop"
"URI::rlogin" "URI::rsync" "URI::rtsp" "URI::rtspu" "URI::sip" "URI::sips"
"URI::snews" "URI::ssh" "URI::telnet" "URI::tn3270" "URI::urn"
"URI::urn::isbn" "URI::urn::oid" "Unicode::Collate" "Unicode::Normalize"
"Unicode::UCD" "User::grent" "User::pwent" "WWW::RobotRules"
"WWW::RobotRules::AnyDBM_File" "XML::Parser" "XML::Parser::Expat"
"XML::Parser::Style::Debug" "XML::Parser::Style::Objects"
"XML::Parser::Style::Stream" "XML::Parser::Style::Subs"
"XML::Parser::Style::Tree" "XS::APItest" "XS::Typemap" "XSLoader" "a2p"
"attributes" "attrs" "autouse" "base" "bigint" "bignum" "bigrat" "blib"
"bytes" "charnames" "constant" "diagnostics" "encoding" "fields" "filetest"
"i686-linux::B" "i686-linux::B::Asmdata" "i686-linux::B::Assembler"
"i686-linux::B::Bblock" "i686-linux::B::Bytecode" "i686-linux::B::C"
"i686-linux::B::CC" "i686-linux::B::Concise" "i686-linux::B::Debug"
"i686-linux::B::Deparse" "i686-linux::B::Disassembler"
"i686-linux::B::Lint" "i686-linux::B::Showlex" "i686-linux::B::Stackobj"
"i686-linux::B::Stash" "i686-linux::B::Terse" "i686-linux::B::Xref"
"i686-linux::ByteLoader" "i686-linux::Compress::Raw::Zlib"
"i686-linux::Config" "i686-linux::Cwd" "i686-linux::DB_File"
"i686-linux::Data::Dumper" "i686-linux::Devel::DProf"
"i686-linux::Devel::PPPort" "i686-linux::Devel::Peek"
"i686-linux::Digest::MD5" "i686-linux::DynaLoader" "i686-linux::Encode"
"i686-linux::Encode::Alias" "i686-linux::Encode::Byte"
"i686-linux::Encode::CJKConstants" "i686-linux::Encode::CN"
"i686-linux::Encode::Config" "i686-linux::Encode::EBCDIC"
"i686-linux::Encode::Encoder" "i686-linux::Encode::Encoding"
"i686-linux::Encode::Guess" "i686-linux::Encode::JP"
"i686-linux::Encode::KR" "i686-linux::Encode::Symbol"
"i686-linux::Encode::TW" "i686-linux::Encode::Unicode" "i686-linux::Errno"
"i686-linux::Fcntl" "i686-linux::File::Glob"
"i686-linux::Filter::Util::Call" "i686-linux::HTML::Entities"
"i686-linux::HTML::Filter" "i686-linux::HTML::HeadParser"
"i686-linux::HTML::LinkExtor" "i686-linux::HTML::Parser"
"i686-linux::HTML::PullParser" "i686-linux::HTML::TokeParser"
"i686-linux::I18N::Langinfo" "i686-linux::IO" "i686-linux::IO::Dir"
"i686-linux::IO::File" "i686-linux::IO::Handle" "i686-linux::IO::Pipe"
"i686-linux::IO::Poll" "i686-linux::IO::Seekable" "i686-linux::IO::Select"
"i686-linux::IO::Socket" "i686-linux::IPC::Msg"
"i686-linux::IPC::Semaphore" "i686-linux::IPC::SysV"
"i686-linux::Image::Magick" "i686-linux::MIME::Base64"
"i686-linux::MIME::QuotedPrint" "i686-linux::O" "i686-linux::Opcode"
"i686-linux::POSIX" "i686-linux::PerlIO::encoding"
"i686-linux::PerlIO::scalar" "i686-linux::PerlIO::via"
"i686-linux::SDBM_File" "i686-linux::Safe" "i686-linux::Socket"
"i686-linux::Storable" "i686-linux::Sys::Hostname"
"i686-linux::Sys::Syslog" "i686-linux::Template"
"i686-linux::Template::Base" "i686-linux::Template::Config"
"i686-linux::Template::Constants" "i686-linux::Template::Context"
"i686-linux::Template::Directive" "i686-linux::Template::Document"
"i686-linux::Template::Exception" "i686-linux::Template::FAQ"
"i686-linux::Template::Filters" "i686-linux::Template::Grammar"
"i686-linux::Template::Iterator" "i686-linux::Template::Library::HTML"
"i686-linux::Template::Library::PostScript"
"i686-linux::Template::Library::Splash" "i686-linux::Template::Manual"
"i686-linux::Template::Manual::Config"
"i686-linux::Template::Manual::Credits"
"i686-linux::Template::Manual::Directives"
"i686-linux::Template::Manual::Filters"
"i686-linux::Template::Manual::Internals"
"i686-linux::Template::Manual::Intro"
"i686-linux::Template::Manual::Plugins"
"i686-linux::Template::Manual::Refs" "i686-linux::Template::Manual::Syntax"
"i686-linux::Template::Manual::VMethods"
"i686-linux::Template::Manual::Variables"
"i686-linux::Template::Manual::Views" "i686-linux::Template::Modules"
"i686-linux::Template::Namespace::Constants" "i686-linux::Template::Parser"
"i686-linux::Template::Plugin" "i686-linux::Template::Plugin::Autoformat"
"i686-linux::Template::Plugin::CGI"
"i686-linux::Template::Plugin::Datafile"
"i686-linux::Template::Plugin::Date"
"i686-linux::Template::Plugin::Directory"
"i686-linux::Template::Plugin::Dumper" "i686-linux::Template::Plugin::File"
"i686-linux::Template::Plugin::Filter"
"i686-linux::Template::Plugin::Format" "i686-linux::Template::Plugin::HTML"
"i686-linux::Template::Plugin::Image"
"i686-linux::Template::Plugin::Iterator"
"i686-linux::Template::Plugin::Pod"
"i686-linux::Template::Plugin::Procedural"
"i686-linux::Template::Plugin::String"
"i686-linux::Template::Plugin::Table" "i686-linux::Template::Plugin::URL"
"i686-linux::Template::Plugin::View" "i686-linux::Template::Plugin::Wrap"
"i686-linux::Template::Plugins" "i686-linux::Template::Provider"
"i686-linux::Template::Service" "i686-linux::Template::Stash"
"i686-linux::Template::Stash::Context" "i686-linux::Template::Stash::XS"
"i686-linux::Template::Test" "i686-linux::Template::Toolkit"
"i686-linux::Template::Tools::tpage" "i686-linux::Template::Tools::ttree"
"i686-linux::Template::Tutorial" "i686-linux::Template::Tutorial::Datafile"
"i686-linux::Template::Tutorial::Web" "i686-linux::Template::VMethods"
"i686-linux::Template::View" "i686-linux::Time::HiRes"
"i686-linux::Unicode::Normalize" "i686-linux::XML::Parser"
"i686-linux::XML::Parser::Expat" "i686-linux::XML::Parser::Style::Debug"
"i686-linux::XML::Parser::Style::Objects"
"i686-linux::XML::Parser::Style::Stream"
"i686-linux::XML::Parser::Style::Subs"
"i686-linux::XML::Parser::Style::Tree" "i686-linux::XS::APItest"
"i686-linux::XS::Typemap" "i686-linux::XSLoader" "i686-linux::attrs"
"i686-linux::encoding" "i686-linux::lib" "i686-linux::ops"
"i686-linux::perllocal" "i686-linux::re" "i686-linux::threads"
"i686-linux::threads::shared" "if" "integer" "less" "lib" "locale"
"lwpcook" "lwptut" "open.pod" "ops" "overload" "perl" "perl5004delta"
"perl5005delta" "perl561delta" "perl56delta" "perl570delta" "perl571delta"
"perl572delta" "perl573delta" "perl581delta" "perl582delta" "perl583delta"
"perl584delta" "perl585delta" "perl586delta" "perl587delta" "perl588delta"
"perl58delta" "perlaix" "perlamiga" "perlapi" "perlapio" "perlapollo"
"perlartistic" "perlbeos" "perlbook" "perlboot" "perlbot" "perlbs2000"
"perlcall" "perlce" "perlcheat" "perlclib" "perlcn" "perlcompile"
"perlcygwin" "perldata" "perldbmfilter" "perldebguts" "perldebtut"
"perldebug" "perldelta" "perldgux" "perldiag" "perldoc" "perldos" "perldsc"
"perlebcdic" "perlembed" "perlepoc" "perlfaq" "perlfaq1" "perlfaq2"
"perlfaq3" "perlfaq4" "perlfaq5" "perlfaq6" "perlfaq7" "perlfaq8"
"perlfaq9" "perlfilter" "perlfork" "perlform" "perlfreebsd" "perlfunc"
"perlglossary" "perlgpl" "perlguts" "perlhack" "perlhist" "perlhpux"
"perlhurd" "perlintern" "perlintro" "perliol" "perlipc" "perlirix" "perljp"
"perlko" "perllexwarn" "perllinux" "perllocal" "perllocale" "perllol"
"perlmachten" "perlmacos" "perlmacosx" "perlmint" "perlmod"
"perlmodinstall" "perlmodlib" "perlmodstyle" "perlmpeix" "perlnetware"
"perlnewmod" "perlnumber" "perlobj" "perlop" "perlopenbsd" "perlopentut"
"perlos2" "perlos390" "perlos400" "perlothrtut" "perlpacktut" "perlplan9"
"perlpod" "perlpodspec" "perlport" "perlqnx" "perlre" "perlref"
"perlreftut" "perlrequick" "perlreref" "perlretut" "perlrun" "perlsec"
"perlsolaris" "perlstyle" "perlsub" "perlsyn" "perlthrtut" "perltie"
"perltoc" "perltodo" "perltooc" "perltoot" "perltrap" "perltru64" "perltw"
"perlunicode" "perluniintro" "perlutil" "perluts" "perlvar" "perlvmesa"
"perlvms" "perlvos" "perlwin32" "perlxs" "perlxstut" "re" "sigtrap"
"sort.pod" "strict" "subs" "threads" "threads::shared" "utf8" "vars"
"vmsish" "warnings" "warnings::register"))
